sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

env: GRADLE_OPTS="-Xmx2500M"
before_install:
  # workaround to get "git describe" working
  - git fetch --unshallow --tags
  - git describe
install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  email: false
 
