sudo: required
dist: trusty

language: java
cache:
  directories:
  - $HOME/.gradle
jdk:
  - openjdk8
  - oraclejdk8

env: GRADLE_OPTS="-Xmx2500M"
before_install:
  # workaround to get "git describe" working
  - git fetch --unshallow --tags
  - git describe
#setupCIWorkspace not needed. At least that's what abrar said.
script: ./gradlew build

notifications:
  email: false
 
